### ISSUE TITLE
Support for Zygisk?

### ISSUE THREAD

**Issue by vaugerbird** [kdrag0n/android12-extensions#11]
Since the LSPosed canary with Zygisk support is now available, I was wondering if a Zygisk version of this is in the works, or even possible without Riru? LSPosed will already recognize Android 12 Extensions in the modules section and allows me to enable it, but the extensions app stills shows the "Xposed module is not enabled" error for obvious reasons.

**Comment by kdrag0n** [comment]
This is an Xposed module that depends on Xposed functionality, so no, there won't be a Zygisk version. Riru and Zygisk alone are not enough; that's why LSPosed itself depends on Riru/Zygisk. Instead, you can install the [Zygisk version of LSPosed](https://t.me/LSPosedArchives) to use this module with Zygisk.
