### ISSUE TITLE
Feature Req: Apply button to apply changes.

### ISSUE THREAD

**Issue by ruhend** [kdrag0n/android12-extensions#4]
In the app, stuff gets applied when changed.
This limits our actions, one edit per UI restart.
Instead, it would be better if there is an apply button on the home screen to apply changes made by the user. 
This enables the user to select desired changes, and then click that apply button to apply changes at once.

**Comment by kdrag0n** [comment]
I've considered this, but I felt that it's more user-friendly to apply changes automatically. "Apply" buttons tend to be prevalent in legacy desktop user interfaces, but I don't remember the last time I've seen one in mobile apps; I typically expect everything to be applied automatically.

With the current UX, you can batch changes by tapping "Cancel" in the "Appylying changes" snackbar. Does this not suffice?

If your issue is that reloads are too intrusive, make sure the module is **disabled** for "System Framework" in LSPosed Manager. Reloads are much faster and less disruptive when it's disabled.

**Comment by ruhend** [comment]
Alright sir, that solves the issue now! Thank you.
